version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "${PORT_EXTERNAL}:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - play2gather-net
    restart: unless-stopped
networks:
  play2gather-net:
    name: play2gather-net
    driver: bridge