app:
  use-dotenv: true
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Rota 1: Para os endpoints de autenticação específicos
        - id: iam-service-auth
          uri: ${IAM_SERVICE_URL}
          predicates:
            - Path=/login, /refresh, /logout
          filters:
            - RewritePath=/(?<segment>.*), /iam/auth/${segment}

        # Rota 2: Para todas as outras rotas que já começam com /iam/
        - id: iam-service-user
          uri: ${IAM_SERVICE_URL}
          predicates:
            - Path=/register, /profile, /update,
          filters:
            - RewritePath=/(?<segment>.*), /iam/user/${segment}

        # Rota específica para o DELETE do usuário
        - id: iam-service-user-delete
          uri: ${IAM_SERVICE_URL}
          predicates:
            - Path=/user
            - Method=DELETE
          filters:
            - SetPath=/iam/user
server:
  port: 8080
logging:
  level:
      root: INFO
      com.play2gather: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [traceId=%X{traceId}] [%t] %c{1} - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %5p [traceId=%X{traceId}] [%t] %c{1} - %m%n"
  file:
      name: logs/gateway.log
  charset:
      console: UTF-8
      file: UTF-8
jwt:
  public-key: ${JWT_PUBLIC_KEY}