app:
  # O valor desta variável será definido pelos perfis abaixo
  iam-service-url: "http://invalid-url"
  cors:
    allowed-origins: ${FRONTEND_URL}

server:
  port: ${PORT_EXTERNAL:8080}

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: iam-service-auth
          uri: ${app.iam-service-url}
          predicates:
            - Path=/login
            - Path=/refresh
            - Path=/logout
          filters:
            - RewritePath=/(?<segment>.*),/iam/auth/${segment}

        - id: iam-service-user
          uri: ${app.iam-service-url}
          predicates:
            - Path=/register
            - Path=/profile
            - Path=/update
          filters:
            - RewritePath=/(?<segment>.*),/iam/user/${segment}

        - id: iam-service-user-delete
          uri: ${app.iam-service-url}
          predicates:
            - Path=/user
            - Method=DELETE
          filters:
            - SetPath=/iam/user

jwt:
  public-key: ${JWT_PUBLIC_KEY}

---
# Perfil PADRÃO (default): para rodar localmente (mvn spring-boot:run)
spring:
  config:
    activate:
      on-profile: default
app:
  iam-service-url: ${IAM_SERVICE_URL_LOCAL}

---
# Perfil DOCKER: para rodar dentro de um container
spring:
  config:
    activate:
      on-profile: docker
app:
  iam-service-url: ${IAM_SERVICE_URL_DOCKER}