spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: exampleRoute
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/exampleyml
          filters:
            - SetPath=/users
server:
  port: 8080