services:
  logger:
    build: .
    ports:
      - "${PORT_EXTERNAL}:8081"
    env_file: .env
    depends_on:
      logger-mongodb:
        condition: service_healthy
    networks:
      - play2gather-net
    restart: unless-stopped
  logger-mongodb:
    image: mongo:7.0
    ports:
      - "${DB_PORT_EXTERNAL}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - logger-mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u ${LOGGER_DB_USER} -p ${LOGGER_DB_PASSWORD} --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      - play2gather-net

volumes:
  logger-mongodb-data: {}

networks:
  play2gather-net:
    name: play2gather-net
    external: true
