version: '3.8'

services:
  iam-db:
    image: postgres:15
    container_name: iam-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - play2gather-net

  iam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iam-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      DOCKER: true
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://iam-db:5432/${DB_NAME}
    depends_on:
      - iam-db
    networks:
      - play2gather-net
volumes:
  postgres_data:

networks:
  play2gather-net:
    external: true