services:
  iam:
    build: .
    ports:
      - "${PORT_EXTERNAL}:8083"
    env_file: .env
    depends_on:
      - iam-postgresql
    networks:
      - play2gather-net
    restart: unless-stopped
  iam-postgresql:
    image: postgres:15
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    container_name: iam-postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - iam-postgres-data:/var/lib/postgresql/data
    networks:
      - play2gather-net
    restart: unless-stopped

volumes:
  iam-postgres-data: {}
networks:
  play2gather-net:
    external: true