server:
  port: ${PORT_EXTERNAL:8081} # Porta interna padrão do container

spring:
  application:
    name: logger

---
# Perfil PADRÃO (default): para rodar localmente (mvn spring-boot:run)
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      uri: ${MONGO_URI_LOCAL}

---
# Perfil DOCKER: para rodar dentro de um container
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: ${MONGO_URI_DOCKER}